/**
 * @file config.cpp
 * @brief Persistent configuration using ESP32 Preferences (NVS)
 */

#include "config.h"
#include "log.h"
#include <Preferences.h>

Config g_config;

static Preferences prefs;
static const char* NVS_NAMESPACE = "btwifi";

void configInit() {
    g_config.setDefaults();
    configLoad();
}

void configLoad() {
    if (!prefs.begin(NVS_NAMESPACE, true)) {  // read-only
        LOG_W("CFG", "NVS namespace not found, using defaults");
        return;
    }

    g_config.serialMode   = (OutputMode)prefs.getUChar("serialMode", (uint8_t)OutputMode::LUA_SERIAL);
    g_config.deviceMode   = (DeviceMode)prefs.getUChar("devMode", (uint8_t)DeviceMode::TRAINER_IN);
    g_config.hasRemoteAddr = prefs.getBool("hasRmtAddr", false);

    String name = prefs.getString("btName", "BTWifiSerial");
    strlcpy(g_config.btName, name.c_str(), sizeof(g_config.btName));

    String lAddr = prefs.getString("localAddr", "");
    strlcpy(g_config.localBtAddr, lAddr.c_str(), sizeof(g_config.localBtAddr));

    String addr = prefs.getString("rmtAddr", "");
    strlcpy(g_config.remoteBtAddr, addr.c_str(), sizeof(g_config.remoteBtAddr));
    g_config.remoteAddrType = prefs.getUChar("rmtAddrType", 0);

    // Telemetry settings
    g_config.telemetryOutput = (TelemetryOutput)prefs.getUChar("telemOut", (uint8_t)TelemetryOutput::WIFI_UDP);
    g_config.udpPort         = prefs.getUShort("udpPort", 5010);
    g_config.sportBaud       = prefs.getULong("sportBaud", 57600);

    // Trainer map mode
    g_config.trainerMapMode  = (TrainerMapMode)prefs.getUChar("mapMode", (uint8_t)TrainerMapMode::MAP_GV);

    // WiFi mode + credentials
    g_config.wifiMode = (WifiMode)prefs.getUChar("wifiMode", (uint8_t)WifiMode::OFF);
    String ssid = prefs.getString("apSsid", "BTWifiSerial");
    strlcpy(g_config.apSsid, ssid.c_str(), sizeof(g_config.apSsid));
    String pass = prefs.getString("apPass", "12345678");
    strlcpy(g_config.apPass, pass.c_str(), sizeof(g_config.apPass));
    String staSsid = prefs.getString("staSsid", "");
    strlcpy(g_config.staSsid, staSsid.c_str(), sizeof(g_config.staSsid));
    String staPass = prefs.getString("staPass", "");
    strlcpy(g_config.staPass, staPass.c_str(), sizeof(g_config.staPass));

    // ELRS Backpack settings
    String elrsBind = prefs.getString("elrsBind", "123456");
    strlcpy(g_config.elrsBindPhrase, elrsBind.c_str(), sizeof(g_config.elrsBindPhrase));

    prefs.end();

    const char* modeStr = "FrSky";
    switch (g_config.serialMode) {
        case OutputMode::SBUS:         modeStr = "SBUS";         break;
        case OutputMode::SPORT_BT:     modeStr = "S.PORT-BT";    break;
        case OutputMode::SPORT_MIRROR: modeStr = "S.PORT-Mirror"; break;
        default: break;
    }
    const char* devStr = "Trainer IN";
    switch (g_config.deviceMode) {
        case DeviceMode::TRAINER_OUT: devStr = "Trainer OUT"; break;
        case DeviceMode::TELEMETRY:   devStr = "Telemetry";   break;
        case DeviceMode::ELRS_HT:     devStr = "ELRS HT";     break;
        default: break;
    }
    LOG_I("CFG", "Loaded: mode=%s dev=%s name=%s", modeStr, devStr, g_config.btName);
}

// ─── Build timestamp ────────────────────────────────────────────────────────
// Generated by scripts/gen_build_ts.py into src/build_ts_gen.h.
// The header is rewritten on every build so this TU is always recompiled,
// keeping the firmware timestamp in sync with build_timestamp.txt.
#include "build_ts_gen.h"
const char* BUILD_TIMESTAMP = BUILD_TS_STR;

void configSave() {
    if (!prefs.begin(NVS_NAMESPACE, false)) {  // read-write
        LOG_E("CFG", "Failed to open NVS for writing");
        return;
    }

    prefs.putUChar("serialMode", (uint8_t)g_config.serialMode);
    prefs.putUChar("devMode", (uint8_t)g_config.deviceMode);
    prefs.putString("btName", g_config.btName);
    prefs.putString("localAddr", g_config.localBtAddr);
    prefs.putString("rmtAddr", g_config.remoteBtAddr);
    prefs.putBool("hasRmtAddr", g_config.hasRemoteAddr);
    prefs.putUChar("rmtAddrType", g_config.remoteAddrType);

    // Telemetry settings
    prefs.putUChar("telemOut", (uint8_t)g_config.telemetryOutput);
    prefs.putUShort("udpPort", g_config.udpPort);
    prefs.putULong("sportBaud", g_config.sportBaud);

    // Trainer map mode
    prefs.putUChar("mapMode", (uint8_t)g_config.trainerMapMode);

    // WiFi mode + credentials
    prefs.putUChar("wifiMode", (uint8_t)g_config.wifiMode);
    prefs.putString("apSsid", g_config.apSsid);
    prefs.putString("apPass", g_config.apPass);
    prefs.putString("staSsid", g_config.staSsid);
    prefs.putString("staPass", g_config.staPass);

    // ELRS Backpack settings
    prefs.putString("elrsBind", g_config.elrsBindPhrase);

    prefs.end();

    LOG_I("CFG", "Settings saved to NVS");
}
